const defaultImages = [
  {
    id: "9VWOr22LhVI",
    slug: "selective-photo-of-green-grains-during-daytime-9VWOr22LhVI",
    created_at: "2013-09-17T13:57:48Z",
    updated_at: "2023-12-12T16:00:03Z",
    promoted_at: "2013-09-17T13:57:48Z",
    width: 5760,
    height: 3840,
    color: "#f3f3f3",
    blur_hash: "L?IrNVkBRkj[~qa#j[j[-=jtoffQ",
    description: "Green ears of wheat",
    alt_description: "selective photo of green grains during daytime",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/12/green.jpg?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/12/green.jpg?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/12/green.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/12/green.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/12/green.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/12/green.jpg",
    },
    links: {
      self: "https://api.unsplash.com/photos/selective-photo-of-green-grains-during-daytime-9VWOr22LhVI",
      html: "https://unsplash.com/photos/selective-photo-of-green-grains-during-daytime-9VWOr22LhVI",
      download:
        "https://unsplash.com/photos/9VWOr22LhVI/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
      download_location:
        "https://api.unsplash.com/photos/9VWOr22LhVI/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
    },
    likes: 1299,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    user: {
      id: "yfQxXqa9MUg",
      updated_at: "2023-09-13T04:32:04Z",
      username: "lukasschweizer",
      name: "Lukas Schweizer",
      first_name: "Lukas",
      last_name: "Schweizer",
      twitter_username: null,
      portfolio_url: "http://www.lukas-schweizer.ch/",
      bio: null,
      location: null,
      links: {
        self: "https://api.unsplash.com/users/lukasschweizer",
        html: "https://unsplash.com/@lukasschweizer",
        photos: "https://api.unsplash.com/users/lukasschweizer/photos",
        likes: "https://api.unsplash.com/users/lukasschweizer/likes",
        portfolio: "https://api.unsplash.com/users/lukasschweizer/portfolio",
        following: "https://api.unsplash.com/users/lukasschweizer/following",
        followers: "https://api.unsplash.com/users/lukasschweizer/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/placeholder-avatars/extra-large.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/placeholder-avatars/extra-large.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/placeholder-avatars/extra-large.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 0,
      total_photos: 1,
      total_promoted_photos: 1,
      accepted_tos: false,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: "http://www.lukas-schweizer.ch/",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: { latitude: null, longitude: null },
    },
    views: 10171202,
    downloads: 50739,
  },
  {
    id: "a1xlQq3HoJ0",
    slug: "gray-concrete-building-a1xlQq3HoJ0",
    created_at: "2018-12-30T05:08:12Z",
    updated_at: "2023-12-13T07:06:47Z",
    promoted_at: "2018-12-31T14:12:43Z",
    width: 2160,
    height: 3840,
    color: "#0c2626",
    blur_hash: "L52jYli_jFkDX9bHfPj[uPbHjYae",
    description: null,
    alt_description: "gray concrete building",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "feelings",
        title: "Feelings Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "cool",
        title: "Cool Images & Photos",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1546146477-15a587cd3fcb?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1546146477-15a587cd3fcb?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1546146477-15a587cd3fcb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1546146477-15a587cd3fcb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1546146477-15a587cd3fcb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1546146477-15a587cd3fcb",
    },
    links: {
      self: "https://api.unsplash.com/photos/gray-concrete-building-a1xlQq3HoJ0",
      html: "https://unsplash.com/photos/gray-concrete-building-a1xlQq3HoJ0",
      download:
        "https://unsplash.com/photos/a1xlQq3HoJ0/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
      download_location:
        "https://api.unsplash.com/photos/a1xlQq3HoJ0/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
    },
    likes: 2944,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: { status: "approved", approved_on: "2020-04-06T14:20:09Z" },
      "architecture-interior": {
        status: "approved",
        approved_on: "2021-04-27T12:20:45Z",
      },
      "textures-patterns": {
        status: "approved",
        approved_on: "2021-04-27T12:20:48Z",
      },
    },
    user: {
      id: "-SGPXoIv0mw",
      updated_at: "2023-09-13T07:16:40Z",
      username: "bradskidley",
      name: "Bradley Jasper Ybanez",
      first_name: "Bradley Jasper",
      last_name: "Ybanez",
      twitter_username: "BradleyYbanez",
      portfolio_url: null,
      bio: null,
      location: "Australia",
      links: {
        self: "https://api.unsplash.com/users/bradskidley",
        html: "https://unsplash.com/@bradskidley",
        photos: "https://api.unsplash.com/users/bradskidley/photos",
        likes: "https://api.unsplash.com/users/bradskidley/likes",
        portfolio: "https://api.unsplash.com/users/bradskidley/portfolio",
        following: "https://api.unsplash.com/users/bradskidley/following",
        followers: "https://api.unsplash.com/users/bradskidley/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1643598847067-4b0c063210f1?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1643598847067-4b0c063210f1?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1643598847067-4b0c063210f1?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 43,
      total_photos: 2,
      total_promoted_photos: 1,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: null,
        twitter_username: "BradleyYbanez",
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: { latitude: null, longitude: null },
    },
    views: 22040728,
    downloads: 223407,
  },
  {
    id: "7eOm_tJMSPE",
    slug: "silhouette-photography-of-coconut-tree-7eOm_tJMSPE",
    created_at: "2018-02-04T19:11:46Z",
    updated_at: "2023-12-12T20:03:40Z",
    promoted_at: "2018-02-05T09:34:13Z",
    width: 5006,
    height: 3265,
    color: "#d9d9d9",
    blur_hash: "LVKU_]~Wo}jZ2bM|s:bHIUWnIUof",
    description:
      "Wandering in the tropical island.\r\nEscape everything to become digital nomad, see the world, be happy, be good",
    alt_description: "silhouette photography of coconut tree",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1517771355228-88102bee3f4a?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1517771355228-88102bee3f4a?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1517771355228-88102bee3f4a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1517771355228-88102bee3f4a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1517771355228-88102bee3f4a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1517771355228-88102bee3f4a",
    },
    links: {
      self: "https://api.unsplash.com/photos/silhouette-photography-of-coconut-tree-7eOm_tJMSPE",
      html: "https://unsplash.com/photos/silhouette-photography-of-coconut-tree-7eOm_tJMSPE",
      download:
        "https://unsplash.com/photos/7eOm_tJMSPE/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
      download_location:
        "https://api.unsplash.com/photos/7eOm_tJMSPE/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
    },
    likes: 391,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    user: {
      id: "mh8-UQUAX3w",
      updated_at: "2023-09-13T07:33:28Z",
      username: "andy_digitalnomad",
      name: "Andy Do",
      first_name: "Andy",
      last_name: "Do",
      twitter_username: null,
      portfolio_url: null,
      bio: "Explorer & Free Spirit \r\nTropical house\r\n Visual Artist & UI Designer\r\n Digital Nomad ",
      location: "Bali",
      links: {
        self: "https://api.unsplash.com/users/andy_digitalnomad",
        html: "https://unsplash.com/@andy_digitalnomad",
        photos: "https://api.unsplash.com/users/andy_digitalnomad/photos",
        likes: "https://api.unsplash.com/users/andy_digitalnomad/likes",
        portfolio: "https://api.unsplash.com/users/andy_digitalnomad/portfolio",
        following: "https://api.unsplash.com/users/andy_digitalnomad/following",
        followers: "https://api.unsplash.com/users/andy_digitalnomad/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1517771715769-f3a1ca85fe67?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1517771715769-f3a1ca85fe67?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1517771715769-f3a1ca85fe67?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "bope_creator",
      total_collections: 0,
      total_likes: 3,
      total_photos: 8,
      total_promoted_photos: 2,
      accepted_tos: false,
      for_hire: false,
      social: {
        instagram_username: "bope_creator",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 550D",
      name: "Canon, EOS 550D",
      exposure_time: "1/160",
      aperture: "5.0",
      focal_length: "18.0",
      iso: 100,
    },
    location: {
      name: "Bali, Indonesia",
      city: null,
      country: "Indonesia",
      position: { latitude: -8.4095178, longitude: 115.188916 },
    },
    views: 8844634,
    downloads: 11081,
  },
  {
    id: "xJEGwEdlkac",
    slug: "brown-and-grey-mountain-xJEGwEdlkac",
    created_at: "2018-12-12T13:34:48Z",
    updated_at: "2023-12-12T18:06:16Z",
    promoted_at: "2018-12-13T07:06:19Z",
    width: 5568,
    height: 3712,
    color: "#d9d9d9",
    blur_hash: "LuKBXbaIM{WB?wxaV@oL9Zt8offR",
    description: null,
    alt_description: "brown and grey mountain",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1544621660-e5e9cec7a5fe?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1544621660-e5e9cec7a5fe?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1544621660-e5e9cec7a5fe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1544621660-e5e9cec7a5fe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1544621660-e5e9cec7a5fe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1544621660-e5e9cec7a5fe",
    },
    links: {
      self: "https://api.unsplash.com/photos/brown-and-grey-mountain-xJEGwEdlkac",
      html: "https://unsplash.com/photos/brown-and-grey-mountain-xJEGwEdlkac",
      download:
        "https://unsplash.com/photos/xJEGwEdlkac/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
      download_location:
        "https://api.unsplash.com/photos/xJEGwEdlkac/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
    },
    likes: 111,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: { status: "approved", approved_on: "2020-04-06T14:20:12Z" },
    },
    user: {
      id: "A-rEQhFdiIA",
      updated_at: "2023-09-13T09:35:58Z",
      username: "desrecits",
      name: "Des Récits",
      first_name: "Des",
      last_name: "Récits",
      twitter_username: null,
      portfolio_url: "http://www.desrecits.com",
      bio: null,
      location: null,
      links: {
        self: "https://api.unsplash.com/users/desrecits",
        html: "https://unsplash.com/@desrecits",
        photos: "https://api.unsplash.com/users/desrecits/photos",
        likes: "https://api.unsplash.com/users/desrecits/likes",
        portfolio: "https://api.unsplash.com/users/desrecits/portfolio",
        following: "https://api.unsplash.com/users/desrecits/following",
        followers: "https://api.unsplash.com/users/desrecits/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1602019205969-13d2c23b24dfimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1602019205969-13d2c23b24dfimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1602019205969-13d2c23b24dfimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "Des_recits",
      total_collections: 0,
      total_likes: 38,
      total_photos: 57,
      total_promoted_photos: 25,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "Des_recits",
        portfolio_url: "http://www.desrecits.com",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: { latitude: null, longitude: null },
    },
    views: 7008293,
    downloads: 6149,
  },
  {
    id: "ysDELCFucFU",
    slug: "birds-eye-view-photography-of-mountain-ysDELCFucFU",
    created_at: "2018-01-24T08:00:34Z",
    updated_at: "2023-12-12T14:04:01Z",
    promoted_at: "2018-01-24T22:37:24Z",
    width: 3648,
    height: 5472,
    color: "#404040",
    blur_hash: "LEFF$?56WAM|_Nof%MbHcF?bIVxt",
    description: "Natural Hot Springs",
    alt_description: "bird's eye view photography of mountain",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1516780715095-8ba27d1c3946?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1516780715095-8ba27d1c3946?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1516780715095-8ba27d1c3946?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1516780715095-8ba27d1c3946?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1516780715095-8ba27d1c3946?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1516780715095-8ba27d1c3946",
    },
    links: {
      self: "https://api.unsplash.com/photos/birds-eye-view-photography-of-mountain-ysDELCFucFU",
      html: "https://unsplash.com/photos/birds-eye-view-photography-of-mountain-ysDELCFucFU",
      download:
        "https://unsplash.com/photos/ysDELCFucFU/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
      download_location:
        "https://api.unsplash.com/photos/ysDELCFucFU/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
    },
    likes: 864,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: { status: "approved", approved_on: "2020-04-15T15:56:36Z" },
    },
    user: {
      id: "fbPZwdKgWWs",
      updated_at: "2023-12-13T07:04:08Z",
      username: "jeremybishop",
      name: "Jeremy Bishop",
      first_name: "Jeremy",
      last_name: "Bishop",
      twitter_username: null,
      portfolio_url: "https://www.jeremybishopphotography.com",
      bio: "I love supporting and inspiring creatives around the world.\r\nMy passion is the ocean and water photography, and I strive to capture the adventure and beauty of this world in the most meaningful ways. ",
      location: "California",
      links: {
        self: "https://api.unsplash.com/users/jeremybishop",
        html: "https://unsplash.com/@jeremybishop",
        photos: "https://api.unsplash.com/users/jeremybishop/photos",
        likes: "https://api.unsplash.com/users/jeremybishop/likes",
        portfolio: "https://api.unsplash.com/users/jeremybishop/portfolio",
        following: "https://api.unsplash.com/users/jeremybishop/following",
        followers: "https://api.unsplash.com/users/jeremybishop/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1610519305252-c9d552283aaaimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1610519305252-c9d552283aaaimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1610519305252-c9d552283aaaimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "schlerm",
      total_collections: 19,
      total_likes: 3592,
      total_photos: 987,
      total_promoted_photos: 498,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "schlerm",
        portfolio_url: "https://www.jeremybishopphotography.com",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 7D Mark II",
      name: "Canon, EOS 7D Mark II",
      exposure_time: "1/250",
      aperture: "4.0",
      focal_length: "50.0",
      iso: 160,
    },
    location: {
      name: "Mammoth Lakes, United States",
      city: "Mammoth Lakes",
      country: "United States",
      position: { latitude: 37.648546, longitude: -118.972079 },
    },
    views: 22412075,
    downloads: 53897,
  },
  {
    id: "p31AHN9FqJc",
    slug: "a-lake-with-a-mountain-in-the-background-at-night-p31AHN9FqJc",
    created_at: "2023-01-02T11:46:56Z",
    updated_at: "2023-12-12T21:42:20Z",
    promoted_at: "2023-01-02T16:42:01Z",
    width: 3712,
    height: 5273,
    color: "#262673",
    blur_hash: "Li7_BhxvoeoMWHWBa#a}IQRiWWWV",
    description: null,
    alt_description: "a lake with a mountain in the background at night",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1672659878782-5862ce1d70d1?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1672659878782-5862ce1d70d1?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1672659878782-5862ce1d70d1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1672659878782-5862ce1d70d1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1672659878782-5862ce1d70d1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1672659878782-5862ce1d70d1",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-lake-with-a-mountain-in-the-background-at-night-p31AHN9FqJc",
      html: "https://unsplash.com/photos/a-lake-with-a-mountain-in-the-background-at-night-p31AHN9FqJc",
      download:
        "https://unsplash.com/photos/p31AHN9FqJc/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
      download_location:
        "https://api.unsplash.com/photos/p31AHN9FqJc/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
    },
    likes: 326,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: { status: "rejected" },
      spirituality: { status: "approved", approved_on: "2023-04-13T13:24:23Z" },
      travel: { status: "approved", approved_on: "2023-01-09T16:23:29Z" },
      nature: { status: "rejected" },
    },
    user: {
      id: "zsp8mlGylOk",
      updated_at: "2023-12-12T02:43:02Z",
      username: "miyatankun",
      name: "Takashi Miyazaki",
      first_name: "Takashi",
      last_name: "Miyazaki",
      twitter_username: null,
      portfolio_url: "https://miyatankun.wixsite.com/miyatankun-photograp",
      bio: "For more photos, visit my portfolio on PIXTA!\r\n",
      location: "Fuchu, Tokyo",
      links: {
        self: "https://api.unsplash.com/users/miyatankun",
        html: "https://unsplash.com/@miyatankun",
        photos: "https://api.unsplash.com/users/miyatankun/photos",
        likes: "https://api.unsplash.com/users/miyatankun/likes",
        portfolio: "https://api.unsplash.com/users/miyatankun/portfolio",
        following: "https://api.unsplash.com/users/miyatankun/following",
        followers: "https://api.unsplash.com/users/miyatankun/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1692692278547-3d0f755f842eimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1692692278547-3d0f755f842eimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1692692278547-3d0f755f842eimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "miyatankun",
      total_collections: 3,
      total_likes: 2587,
      total_photos: 171,
      total_promoted_photos: 22,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "miyatankun",
        portfolio_url: "https://miyatankun.wixsite.com/miyatankun-photograp",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "NIKON CORPORATION",
      model: "NIKON D500",
      name: "NIKON CORPORATION, NIKON D500",
      exposure_time: "13",
      aperture: "3.8",
      focal_length: "12.0",
      iso: 1000,
    },
    location: {
      name: "Lake Kawaguchi, 富士河口湖町 山梨県 日本",
      city: "富士河口湖町",
      country: "日本",
      position: { latitude: 35.517095, longitude: 138.751779 },
    },
    views: 7395849,
    downloads: 93940,
  },
  {
    id: "EpnxcHT-fz8",
    slug: "a-large-castle-with-towers-on-top-of-a-hill-EpnxcHT-fz8",
    created_at: "2019-02-12T16:12:26Z",
    updated_at: "2023-12-13T02:07:35Z",
    promoted_at: "2019-02-14T14:10:50Z",
    width: 4288,
    height: 2848,
    color: "#f3f3f3",
    blur_hash: "LvPP_xofWBof~qjtf6ay9FfPazay",
    description: null,
    alt_description: "a large castle with towers on top of a hill",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1549987506-49d8c191cb94?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1549987506-49d8c191cb94?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1549987506-49d8c191cb94?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1549987506-49d8c191cb94?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1549987506-49d8c191cb94?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1549987506-49d8c191cb94",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-large-castle-with-towers-on-top-of-a-hill-EpnxcHT-fz8",
      html: "https://unsplash.com/photos/a-large-castle-with-towers-on-top-of-a-hill-EpnxcHT-fz8",
      download:
        "https://unsplash.com/photos/EpnxcHT-fz8/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
      download_location:
        "https://api.unsplash.com/photos/EpnxcHT-fz8/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
    },
    likes: 153,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: { status: "approved", approved_on: "2021-09-08T12:10:40Z" },
    },
    user: {
      id: "ux-4bOkUpPE",
      updated_at: "2023-09-12T22:55:57Z",
      username: "jennieramida",
      name: "jennieramida",
      first_name: "jennieramida",
      last_name: null,
      twitter_username: "jennieramida",
      portfolio_url: null,
      bio: "UX Designer / Front-end Developer\r\nBased in Bangkok, Thailand",
      location: null,
      links: {
        self: "https://api.unsplash.com/users/jennieramida",
        html: "https://unsplash.com/@jennieramida",
        photos: "https://api.unsplash.com/users/jennieramida/photos",
        likes: "https://api.unsplash.com/users/jennieramida/likes",
        portfolio: "https://api.unsplash.com/users/jennieramida/portfolio",
        following: "https://api.unsplash.com/users/jennieramida/following",
        followers: "https://api.unsplash.com/users/jennieramida/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-fb-1534669984-beeff76539a9.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-fb-1534669984-beeff76539a9.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-fb-1534669984-beeff76539a9.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "jennieramida",
      total_collections: 3,
      total_likes: 10,
      total_photos: 57,
      total_promoted_photos: 5,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "jennieramida",
        portfolio_url: null,
        twitter_username: "jennieramida",
        paypal_email: null,
      },
    },
    exif: {
      make: "NIKON CORPORATION",
      model: "NIKON D90",
      name: "NIKON CORPORATION, NIKON D90",
      exposure_time: "1/800",
      aperture: "4.5",
      focal_length: "18.0",
      iso: 200,
    },
    location: {
      name: "Neuschwanstien, Füssen, Germany",
      city: "Füssen",
      country: "Germany",
      position: { latitude: null, longitude: null },
    },
    views: 6521231,
    downloads: 5875,
  },
  {
    id: "oGAB1BkqCp4",
    slug: "surfboard-about-to-meet-wild-waves-oGAB1BkqCp4",
    created_at: "2016-10-07T14:58:29Z",
    updated_at: "2023-12-13T04:01:02Z",
    promoted_at: "2016-10-07T14:58:29Z",
    width: 5184,
    height: 3456,
    color: "#c0c0d9",
    blur_hash: "LdIiCGMwM{j]_Nx^RjaxM_aeogof",
    description: "Rocky beach surfing",
    alt_description: "surfboard about to meet wild waves",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1475850353411-26df570ed0ab?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1475850353411-26df570ed0ab?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1475850353411-26df570ed0ab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1475850353411-26df570ed0ab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1475850353411-26df570ed0ab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1475850353411-26df570ed0ab",
    },
    links: {
      self: "https://api.unsplash.com/photos/surfboard-about-to-meet-wild-waves-oGAB1BkqCp4",
      html: "https://unsplash.com/photos/surfboard-about-to-meet-wild-waves-oGAB1BkqCp4",
      download:
        "https://unsplash.com/photos/oGAB1BkqCp4/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
      download_location:
        "https://api.unsplash.com/photos/oGAB1BkqCp4/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
    },
    likes: 526,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    user: {
      id: "xu2IxF26ZAw",
      updated_at: "2023-09-02T05:04:46Z",
      username: "olyester",
      name: "Oliver Raatz",
      first_name: "Oliver",
      last_name: "Raatz",
      twitter_username: "oraatz",
      portfolio_url: "http://www.oliverraatz.de/film-fotos",
      bio: "Home on water. Cruising & kiting along the shores of Northern Europe. Adventure seeker. UX Creative Director based in Hamburg, Germany",
      location: "Hamburg",
      links: {
        self: "https://api.unsplash.com/users/olyester",
        html: "https://unsplash.com/@olyester",
        photos: "https://api.unsplash.com/users/olyester/photos",
        likes: "https://api.unsplash.com/users/olyester/likes",
        portfolio: "https://api.unsplash.com/users/olyester/portfolio",
        following: "https://api.unsplash.com/users/olyester/following",
        followers: "https://api.unsplash.com/users/olyester/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1517475949793-a2460d65f88f?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1517475949793-a2460d65f88f?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1517475949793-a2460d65f88f?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "oliverraatz",
      total_collections: 2,
      total_likes: 137,
      total_photos: 5,
      total_promoted_photos: 2,
      accepted_tos: false,
      for_hire: false,
      social: {
        instagram_username: "oliverraatz",
        portfolio_url: "http://www.oliverraatz.de/film-fotos",
        twitter_username: "oraatz",
        paypal_email: null,
      },
    },
    exif: {
      make: "Panasonic",
      model: "DMC-GX8",
      name: "Panasonic, DMC-GX8",
      exposure_time: "1/640",
      aperture: "6.3",
      focal_length: "400.0",
      iso: 250,
    },
    location: {
      name: "Klitmøller, Denmark",
      city: "Klitmøller",
      country: "Denmark",
      position: { latitude: 57.0400556, longitude: 8.49328730000002 },
    },
    views: 6765423,
    downloads: 12749,
  },
  {
    id: "NwJ-bJk4VRE",
    slug: "a-lake-surrounded-by-mountains-and-trees-NwJ-bJk4VRE",
    created_at: "2023-08-15T07:45:46Z",
    updated_at: "2023-12-13T04:44:27Z",
    promoted_at: "2023-08-16T19:32:01Z",
    width: 3024,
    height: 4032,
    color: "#262626",
    blur_hash: "LeEpp3xtVYRi.At7R%WBo$NHkXoJ",
    description: "Drone shot of Lago di Braies.",
    alt_description: "a lake surrounded by mountains and trees",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1692085450034-3e7b05de83ed?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1692085450034-3e7b05de83ed?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1692085450034-3e7b05de83ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1692085450034-3e7b05de83ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1692085450034-3e7b05de83ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1692085450034-3e7b05de83ed",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-lake-surrounded-by-mountains-and-trees-NwJ-bJk4VRE",
      html: "https://unsplash.com/photos/a-lake-surrounded-by-mountains-and-trees-NwJ-bJk4VRE",
      download:
        "https://unsplash.com/photos/NwJ-bJk4VRE/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
      download_location:
        "https://api.unsplash.com/photos/NwJ-bJk4VRE/download?ixid=M3w1MzE0MzB8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDI0NjM5NzZ8",
    },
    likes: 215,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    user: {
      id: "hvSa9L-6yyM",
      updated_at: "2023-11-24T06:56:47Z",
      username: "finge",
      name: "Finge Holden",
      first_name: "Finge",
      last_name: "Holden",
      twitter_username: "finge",
      portfolio_url: null,
      bio: null,
      location: "Trondheim, Norway",
      links: {
        self: "https://api.unsplash.com/users/finge",
        html: "https://unsplash.com/@finge",
        photos: "https://api.unsplash.com/users/finge/photos",
        likes: "https://api.unsplash.com/users/finge/likes",
        portfolio: "https://api.unsplash.com/users/finge/portfolio",
        following: "https://api.unsplash.com/users/finge/following",
        followers: "https://api.unsplash.com/users/finge/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1691597081905-b1402eeb4c4dimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1691597081905-b1402eeb4c4dimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1691597081905-b1402eeb4c4dimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "finge",
      total_collections: 0,
      total_likes: 4,
      total_photos: 12,
      total_promoted_photos: 6,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "finge",
        portfolio_url: null,
        twitter_username: "finge",
        paypal_email: null,
      },
    },
    exif: {
      make: "DJI",
      model: "FC3582",
      name: "DJI, FC3582",
      exposure_time: "1/1250",
      aperture: "1.7",
      focal_length: "6.7",
      iso: 150,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: { latitude: 0, longitude: 0 },
    },
    views: 2743313,
    downloads: 63145,
  },
];

export { defaultImages };
